[project]
name = "heftie-textbook"
version = "0.1.0"
description = "A digital textbook for working with huge 3D imaging datasets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-book==1.0.3",
    "matplotlib==3.9.2",
    "numpy==2.1.2",
    "sphinx==8.1.3",
]

[tool.setuptools]
packages = []
